/* ==========================================================================
   SPORTS FRIENDS — catalogue
   A starter list of common sports-shop items. Edit freely:
   - Remove anything the shop doesn't sell, add what it does.
   - `price` is optional. Example: price: "From ₹450"  (otherwise only the "Ask price" button is shown)
   - `image` is optional. Put a photo in images/products/ and set
     image: "images/products/kashmir-bat.jpg"  (otherwise a sport icon is shown)
   - `icon` picks the drawing used when there is no photo (see js/icons.js).
   - `tags` are extra search words, including Hindi words typed in English.
   - `featured: true` items are shown first; the rest appear after "Show all".
   ========================================================================== */

window.CATEGORIES = [
  { id: "cricket",     icon: "bat",        tint: "#FFF1E6", ink: "#C2410C", name: { en: "Cricket",            hi: "क्रिकेट" } },
  { id: "football",    icon: "football",   tint: "#E7F6EC", ink: "#15803D", name: { en: "Football",           hi: "फुटबॉल" } },
  { id: "badminton",   icon: "shuttle",    tint: "#ECEFFE", ink: "#4338CA", name: { en: "Badminton",          hi: "बैडमिंटन" } },
  { id: "volleyball",  icon: "volleyball", tint: "#FDF6D8", ink: "#A16207", name: { en: "Volleyball",         hi: "वॉलीबॉल" } },
  { id: "tabletennis", icon: "ttbat",      tint: "#FFE7EA", ink: "#BE123C", name: { en: "Table tennis",       hi: "टेबल टेनिस" } },
  { id: "fitness",     icon: "dumbbell",   tint: "#E3F2FD", ink: "#0369A1", name: { en: "Fitness",            hi: "फिटनेस" } },
  { id: "footwear",    icon: "shoe",       tint: "#F3EAFD", ink: "#7E22CE", name: { en: "Shoes",              hi: "जूते" } },
  { id: "apparel",     icon: "jersey",     tint: "#DDF7F1", ink: "#0F766E", name: { en: "Sportswear",         hi: "स्पोर्ट्सवियर" } },
  { id: "indoor",      icon: "carrom",     tint: "#FBEAFD", ink: "#A21CAF", name: { en: "Indoor games",       hi: "इनडोर गेम्स" } },
  { id: "awards",      icon: "trophy",     tint: "#FEF2D6", ink: "#B45309", name: { en: "Trophies & medals",  hi: "ट्रॉफी और मेडल" } }
];

window.PRODUCTS = [
  // ---- Cricket -----------------------------------------------------------
  { id: "kashmir-willow-bat", cat: "cricket", icon: "bat", featured: true,
    name: { en: "Kashmir willow cricket bat", hi: "कश्मीर विलो क्रिकेट बैट" },
    desc: { en: "Sturdy all-rounder for leather and tennis-ball games.", hi: "लेदर और टेनिस बॉल दोनों के लिए मज़बूत बैट।" },
    tags: ["bat", "balla", "willow", "kashmir"] },
  { id: "english-willow-bat", cat: "cricket", icon: "bat",
    name: { en: "English willow cricket bat", hi: "इंग्लिश विलो क्रिकेट बैट" },
    desc: { en: "Premium willow for serious leather-ball players.", hi: "लेदर बॉल के गंभीर खिलाड़ियों के लिए प्रीमियम बैट।" },
    tags: ["bat", "balla", "willow", "english", "leather"] },
  { id: "tennis-cricket-bat", cat: "cricket", icon: "bat",
    name: { en: "Tennis-ball cricket bat", hi: "टेनिस बॉल क्रिकेट बैट" },
    desc: { en: "Light bat for street and tape-ball cricket.", hi: "गली और टेप-बॉल क्रिकेट के लिए हल्का बैट।" },
    tags: ["bat", "balla", "tennis", "tape", "plastic"] },
  { id: "leather-ball", cat: "cricket", icon: "cricketball",
    name: { en: "Leather cricket ball", hi: "लेदर क्रिकेट बॉल" },
    desc: { en: "Red and white balls for matches and nets.", hi: "मैच और नेट प्रैक्टिस के लिए लाल और सफ़ेद बॉल।" },
    tags: ["ball", "gend", "leather", "season"] },
  { id: "heavy-tennis-ball", cat: "cricket", icon: "tennisball",
    name: { en: "Heavy tennis ball", hi: "हेवी टेनिस बॉल" },
    desc: { en: "The tennis-ball cricket favourite.", hi: "टेनिस बॉल क्रिकेट की पहली पसंद।" },
    tags: ["ball", "gend", "tennis", "tape"] },
  { id: "batting-pads", cat: "cricket", icon: "pads",
    name: { en: "Batting pads", hi: "बैटिंग पैड" },
    desc: { en: "Leg guards for batters and wicket-keepers.", hi: "बल्लेबाज़ों और विकेटकीपर के लिए लेग गार्ड।" },
    tags: ["pad", "pads", "leg guard", "keeper"] },
  { id: "batting-gloves", cat: "cricket", icon: "glove",
    name: { en: "Batting gloves", hi: "बैटिंग ग्लव्स" },
    desc: { en: "Padded gloves for a safe, firm grip.", hi: "सुरक्षित और मज़बूत पकड़ के लिए पैडेड ग्लव्स।" },
    tags: ["gloves", "glove", "dastane"] },
  { id: "cricket-helmet", cat: "cricket", icon: "helmet",
    name: { en: "Cricket helmet", hi: "क्रिकेट हेलमेट" },
    desc: { en: "Head and face protection for batters.", hi: "बल्लेबाज़ के सिर और चेहरे की सुरक्षा।" },
    tags: ["helmet", "safety"] },
  { id: "stumps-set", cat: "cricket", icon: "stumps",
    name: { en: "Stumps set", hi: "स्टंप सेट" },
    desc: { en: "Stumps and bails for matches and practice.", hi: "मैच और प्रैक्टिस के लिए स्टंप और बेल्स।" },
    tags: ["stumps", "wicket", "bails"] },
  { id: "cricket-kit-bag", cat: "cricket", icon: "bag",
    name: { en: "Cricket kit bag", hi: "क्रिकेट किट बैग" },
    desc: { en: "Carry your bat, pads and gear together.", hi: "बैट, पैड और सारा सामान एक साथ रखें।" },
    tags: ["bag", "kit", "kitbag"] },

  // ---- Football ----------------------------------------------------------
  { id: "football-size-5", cat: "football", icon: "football", featured: true,
    name: { en: "Football – size 5", hi: "फुटबॉल – साइज़ 5" },
    desc: { en: "Full-size ball for matches and training.", hi: "मैच और ट्रेनिंग के लिए फुल-साइज़ बॉल।" },
    tags: ["ball", "football", "soccer", "size 5"] },
  { id: "football-junior", cat: "football", icon: "football",
    name: { en: "Football – size 3 & 4", hi: "फुटबॉल – साइज़ 3 और 4" },
    desc: { en: "Smaller balls for kids and juniors.", hi: "बच्चों और जूनियर्स के लिए छोटी बॉल।" },
    tags: ["ball", "football", "soccer", "kids", "junior"] },
  { id: "football-studs", cat: "football", icon: "shoe",
    name: { en: "Football studs", hi: "फुटबॉल स्टड्स" },
    desc: { en: "Boots with grip for grass and ground play.", hi: "घास और मैदान पर अच्छी पकड़ वाले जूते।" },
    tags: ["studs", "boots", "shoes", "joota", "juta"] },
  { id: "shin-guards", cat: "football", icon: "shinguard",
    name: { en: "Shin guards", hi: "शिन गार्ड" },
    desc: { en: "Light protection for match days.", hi: "मैच के दिन के लिए हल्की सुरक्षा।" },
    tags: ["shin", "guard", "pad"] },
  { id: "goalkeeper-gloves", cat: "football", icon: "glove",
    name: { en: "Goalkeeper gloves", hi: "गोलकीपर ग्लव्स" },
    desc: { en: "Padded palms for safe catches.", hi: "सुरक्षित कैच के लिए पैडेड हथेली।" },
    tags: ["gloves", "keeper", "goalkeeper"] },

  // ---- Badminton ---------------------------------------------------------
  { id: "badminton-racket", cat: "badminton", icon: "racket", featured: true,
    name: { en: "Badminton racket", hi: "बैडमिंटन रैकेट" },
    desc: { en: "Light frames for beginners and regular players.", hi: "शुरुआती और रोज़ खेलने वालों के लिए हल्के रैकेट।" },
    tags: ["racket", "racquet", "badminton"] },
  { id: "feather-shuttles", cat: "badminton", icon: "shuttle",
    name: { en: "Feather shuttlecocks", hi: "फेदर शटलकॉक" },
    desc: { en: "True flight for indoor courts.", hi: "इनडोर कोर्ट के लिए सही उड़ान।" },
    tags: ["shuttle", "cock", "feather", "chidiya"] },
  { id: "nylon-shuttles", cat: "badminton", icon: "shuttle",
    name: { en: "Nylon shuttlecocks", hi: "नायलॉन शटलकॉक" },
    desc: { en: "Long-lasting, good for outdoor play.", hi: "टिकाऊ, बाहर खेलने के लिए अच्छे।" },
    tags: ["shuttle", "cock", "nylon", "plastic", "chidiya"] },
  { id: "badminton-net", cat: "badminton", icon: "net",
    name: { en: "Badminton net", hi: "बैडमिंटन नेट" },
    desc: { en: "For courts, schools and backyards.", hi: "कोर्ट, स्कूल और आंगन के लिए।" },
    tags: ["net", "jaal"] },
  { id: "racket-grip", cat: "badminton", icon: "grip",
    name: { en: "Racket grips", hi: "रैकेट ग्रिप" },
    desc: { en: "Fresh grip for a better hold.", hi: "बेहतर पकड़ के लिए नई ग्रिप।" },
    tags: ["grip", "tape", "racket"] },

  // ---- Volleyball --------------------------------------------------------
  { id: "volleyball", cat: "volleyball", icon: "volleyball", featured: true,
    name: { en: "Volleyball", hi: "वॉलीबॉल" },
    desc: { en: "For school games and outdoor courts.", hi: "स्कूल के खेल और बाहर के कोर्ट के लिए।" },
    tags: ["ball", "volley"] },
  { id: "volleyball-net", cat: "volleyball", icon: "net",
    name: { en: "Volleyball net", hi: "वॉलीबॉल नेट" },
    desc: { en: "Durable nets for regular play.", hi: "रोज़ के खेल के लिए मज़बूत नेट।" },
    tags: ["net", "jaal"] },

  // ---- Table tennis ------------------------------------------------------
  { id: "tt-bat", cat: "tabletennis", icon: "ttbat",
    name: { en: "Table tennis bat", hi: "टेबल टेनिस बैट" },
    desc: { en: "Paddles for practice and matches.", hi: "प्रैक्टिस और मैच के लिए बैट।" },
    tags: ["tt", "paddle", "bat", "ping pong"] },
  { id: "tt-balls", cat: "tabletennis", icon: "ttballs",
    name: { en: "Table tennis balls", hi: "टेबल टेनिस बॉल" },
    desc: { en: "Practice and match balls.", hi: "प्रैक्टिस और मैच के लिए बॉल।" },
    tags: ["tt", "ball", "ping pong"] },

  // ---- Fitness -----------------------------------------------------------
  { id: "dumbbells", cat: "fitness", icon: "dumbbell", featured: true,
    name: { en: "Dumbbells", hi: "डम्बल" },
    desc: { en: "Home workout essentials.", hi: "घर पर कसरत के लिए ज़रूरी।" },
    tags: ["gym", "weights", "dumbell"] },
  { id: "skipping-rope", cat: "fitness", icon: "rope",
    name: { en: "Skipping rope", hi: "स्किपिंग रोप (रस्सी)" },
    desc: { en: "Cardio, warm-ups and stamina.", hi: "कार्डियो, वॉर्म-अप और स्टैमिना के लिए।" },
    tags: ["rope", "rassi", "jump"] },
  { id: "yoga-mat", cat: "fitness", icon: "mat",
    name: { en: "Yoga mat", hi: "योगा मैट" },
    desc: { en: "Non-slip mat for yoga and floor exercises.", hi: "योग और फ़्लोर एक्सरसाइज़ के लिए फिसलन-रोधी मैट।" },
    tags: ["yoga", "mat"] },
  { id: "resistance-bands", cat: "fitness", icon: "band",
    name: { en: "Resistance bands", hi: "रेज़िस्टेंस बैंड" },
    desc: { en: "Strength and stretching anywhere.", hi: "कहीं भी ताकत और स्ट्रेचिंग।" },
    tags: ["band", "gym", "stretch"] },
  { id: "hand-gripper", cat: "fitness", icon: "gripper",
    name: { en: "Hand gripper", hi: "हैंड ग्रिपर" },
    desc: { en: "Build forearm and grip strength.", hi: "कलाई और पकड़ मज़बूत करें।" },
    tags: ["gripper", "gym", "hand"] },

  // ---- Shoes -------------------------------------------------------------
  { id: "running-shoes", cat: "footwear", icon: "shoe", featured: true,
    name: { en: "Running shoes", hi: "रनिंग शूज़" },
    desc: { en: "Cushioned shoes for running and training.", hi: "दौड़ और ट्रेनिंग के लिए आरामदायक जूते।" },
    tags: ["shoes", "joota", "juta", "sports shoes"] },
  { id: "kids-sports-shoes", cat: "footwear", icon: "shoe",
    name: { en: "Kids' sports shoes", hi: "बच्चों के स्पोर्ट्स शूज़" },
    desc: { en: "For school sports and PT.", hi: "स्कूल स्पोर्ट्स और पीटी के लिए।" },
    tags: ["shoes", "joota", "juta", "kids", "school", "pt"] },
  { id: "sports-socks", cat: "footwear", icon: "sock",
    name: { en: "Sports socks", hi: "स्पोर्ट्स मोज़े" },
    desc: { en: "Ankle and full-length pairs.", hi: "एंकल और फुल-लेंथ मोज़े।" },
    tags: ["socks", "moze", "moja"] },

  // ---- Sportswear --------------------------------------------------------
  { id: "team-jerseys", cat: "apparel", icon: "jersey", featured: true,
    name: { en: "Team jerseys", hi: "टीम जर्सी" },
    desc: { en: "For football, cricket and more.", hi: "फुटबॉल, क्रिकेट और दूसरे खेलों के लिए।" },
    tags: ["jersey", "tshirt", "team", "kit"] },
  { id: "track-pants", cat: "apparel", icon: "pants",
    name: { en: "Track pants", hi: "ट्रैक पैंट" },
    desc: { en: "For training and everyday wear.", hi: "ट्रेनिंग और रोज़ पहनने के लिए।" },
    tags: ["lower", "trackpant", "pant"] },
  { id: "sports-tshirts", cat: "apparel", icon: "tshirt",
    name: { en: "Sports T-shirts", hi: "स्पोर्ट्स टी-शर्ट" },
    desc: { en: "Breathable fabric for hot days.", hi: "गर्मी के दिनों के लिए हवादार कपड़ा।" },
    tags: ["tshirt", "t-shirt", "dri fit"] },
  { id: "sports-shorts", cat: "apparel", icon: "shorts",
    name: { en: "Sports shorts", hi: "स्पोर्ट्स शॉर्ट्स" },
    desc: { en: "Light shorts for training and matches.", hi: "ट्रेनिंग और मैच के लिए हल्के शॉर्ट्स।" },
    tags: ["shorts", "half pant", "nikar"] },

  // ---- Indoor games ------------------------------------------------------
  { id: "carrom-board", cat: "indoor", icon: "carrom", featured: true,
    name: { en: "Carrom board", hi: "कैरम बोर्ड" },
    desc: { en: "Smooth boards for family and club play.", hi: "परिवार और क्लब में खेलने के लिए चिकना बोर्ड।" },
    tags: ["carrom", "board", "caram"] },
  { id: "carrom-coins", cat: "indoor", icon: "striker",
    name: { en: "Carrom coins & striker", hi: "कैरम गोटी और स्ट्राइकर" },
    desc: { en: "Coins, strikers and board powder.", hi: "गोटी, स्ट्राइकर और बोर्ड पाउडर।" },
    tags: ["carrom", "coins", "goti", "striker", "powder"] },
  { id: "chess-set", cat: "indoor", icon: "pawn",
    name: { en: "Chess set", hi: "शतरंज सेट" },
    desc: { en: "Board and pieces for home and school.", hi: "घर और स्कूल के लिए बोर्ड और मोहरे।" },
    tags: ["chess", "shatranj"] },
  { id: "ludo-board-games", cat: "indoor", icon: "dice",
    name: { en: "Ludo & board games", hi: "लूडो और बोर्ड गेम्स" },
    desc: { en: "Games for the whole family.", hi: "पूरे परिवार के लिए खेल।" },
    tags: ["ludo", "snakes", "ladders", "dice"] },

  // ---- Trophies & medals -------------------------------------------------
  { id: "trophies", cat: "awards", icon: "trophy",
    name: { en: "Trophies", hi: "ट्रॉफी" },
    desc: { en: "For tournaments, schools and events.", hi: "टूर्नामेंट, स्कूल और कार्यक्रमों के लिए।" },
    tags: ["trophy", "cup", "award", "prize"] },
  { id: "medals", cat: "awards", icon: "medal",
    name: { en: "Medals", hi: "मेडल" },
    desc: { en: "Gold, silver and bronze finishes.", hi: "गोल्ड, सिल्वर और ब्रॉन्ज़ फ़िनिश।" },
    tags: ["medal", "award", "prize"] }
];
